name: GitHub Actions
on: [push]
jobs:
  run:
    runs-on: self-hosted
    permissions:
      id-token: 'write'

    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.3.0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/206298843774/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider'
        service_account: 'gh-runner@gke-project-307320.iam.gserviceaccount.com'

    # Example of using the token:
    - name: 'Access secret'
      run: |-
        curl https://secretmanager.googleapis.com/v1/projects/gke-project-307320/secrets/my-secret/versions/1:access \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
